In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
testdf= pd.read_csv('test_AV3.csv')
testdf.head(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0  LP001015    Male     Yes          0      Graduate            No   
1  LP001022    Male     Yes          1      Graduate            No   
2  LP001031    Male     Yes          2      Graduate            No   
3  LP001035    Male     Yes          2      Graduate            No   
4  LP001051    Male      No          0  Not Graduate            No   
5  LP001054    Male     Yes          0  Not Graduate           Yes   
6  LP001055  Female      No          1  Not Graduate            No   
7  LP001056    Male     Yes          2  Not Graduate            No   
8  LP001059    Male     Yes          2      Graduate           NaN   
9  LP001067    Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   
5             2165               3422       152.0             360.0   
6             2226                  0        59.0             360.0   
7             3881                  0       147.0             360.0   
8            13633                  0       280.0             240.0   
9             2400               2400       123.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Urban           Y  
2             1.0         Urban           Y  
3             NaN         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0     Semiurban           Y  
7             0.0         Rural           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           Y

In [8]:
testdf.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       367.000000         367.000000  362.000000        361.000000   
mean       4805.599455        1569.577657  136.132597        342.537396   
std        4910.685399        2334.232099   61.366652         65.156643   
min           0.000000           0.000000   28.000000          6.000000   
25%        2864.000000           0.000000  100.250000        360.000000   
50%        3786.000000        1025.000000  125.000000        360.000000   
75%        5060.000000        2430.500000  158.000000        360.000000   
max       72529.000000       24000.000000  550.000000        480.000000   

       Credit_History  
count      338.000000  
mean         0.825444  
std          0.380150  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

# Handling Null Values 

In [9]:
# Analysing null values
null_columns= testdf.columns[testdf.isnull().any()]
testdf[null_columns].isnull().sum()

Gender              11
Dependents          10
Self_Employed       23
LoanAmount           5
Loan_Amount_Term     6
Credit_History      29
dtype: int64

In [11]:
### Handling null values in LoanAmount
meanMale= testdf.loc[testdf.Gender=="Male", 'LoanAmount'].mean()
meanFemale= testdf.loc[ testdf.Gender=='Female', 'LoanAmount'].mean()
print(meanMale)
print(meanFemale)

#For Males
testdf.loc[( testdf.LoanAmount.isnull() ) & (testdf.Gender=='Male') , 'LoanAmount']= meanMale

#For Females
testdf.loc[( testdf.LoanAmount.isnull() ) & (testdf.Gender=='Female') , 'LoanAmount']= meanFemale

testdf.loc[testdf.LoanAmount.isnull()]

139.03191489361703
126.79710144927537


Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [13]:
### Handling null values in Loan_Amount_Term
testdf.loc[testdf.Loan_Amount_Term.isnull()].head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
45   LP001232   Male     Yes          0      Graduate            No   
48   LP001268   Male      No          0      Graduate            No   
117  LP001611   Male     Yes          1      Graduate            No   
129  LP001695   Male     Yes          1  Not Graduate            No   
184  LP002045   Male     Yes         3+      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
45              4260               3900       185.0               NaN   
48              6792               3338       187.0               NaN   
117             1516               2900        80.0               NaN   
129             3321               2088        70.0               NaN   
184            10166                750       150.0               NaN   

     Credit_History Property_Area Loan_Status  
45              NaN         Urban           Y  
48              1.0         Urban           Y  
117             0.0         Rural           N  
129             1.0     Semiurban           Y  
184             1.0         Urban           Y

In [15]:
meanMale= testdf.loc[testdf.Gender=="Male", 'Loan_Amount_Term'].mean()
meanFemale= testdf.loc[ testdf.Gender=='Female', 'Loan_Amount_Term'].mean()
print(meanMale)
print(meanFemale)
#For Males
testdf.loc[( testdf.Loan_Amount_Term.isnull() ) & (testdf.Gender=='Male') , 'Loan_Amount_Term']= meanMale

#For Females
testdf.loc[( testdf.Loan_Amount_Term.isnull() ) & (testdf.Gender=='Female') , 'Loan_Amount_Term']= meanFemale

testdf.loc[testdf.Loan_Amount_Term.isnull()]

340.4
350.9142857142857


Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [17]:
### Handling null values in Credit_History
testdf.loc[testdf.Credit_History.isnull()].head()

Loan_ID Gender Married Dependents Education Self_Employed  \
3   LP001035   Male     Yes          2  Graduate            No   
12  LP001083   Male      No         3+  Graduate            No   
26  LP001163   Male     Yes          2  Graduate            No   
28  LP001174   Male     Yes          0  Graduate            No   
45  LP001232   Male     Yes          0  Graduate            No   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
3              2340               2546       100.0             360.0   
12             4166                  0        40.0             180.0   
26             4363               1250       140.0             360.0   
28             3772                833        57.0             360.0   
45             4260               3900       185.0             340.4   

    Credit_History Property_Area Loan_Status  
3              NaN         Urban           Y  
12             NaN         Urban           Y  
26             NaN         Urban           Y  
28             NaN     Semiurban           Y  
45             NaN         Urban           Y

In [19]:
meanMale= testdf.loc[testdf.Gender=="Male", 'Credit_History'].mean()
meanFemale= testdf.loc[ testdf.Gender=='Female', 'Credit_History'].mean()
print(meanMale)
print(meanFemale)
#For Males
testdf.loc[( testdf.Credit_History.isnull() ) & (testdf.Gender=='Male') , 'Credit_History']= meanMale

#For Females
testdf.loc[( testdf.Credit_History.isnull() ) & (testdf.Gender=='Female') , 'Credit_History']= meanFemale

testdf.loc[testdf.Credit_History.isnull()]

0.8326996197718631
0.796875


Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [37]:
#analysis
null_columns= testdf.columns[testdf.isnull().any()]
testdf[null_columns].isnull().sum()

Gender        11
Dependents    10
dtype: int64

In [23]:
### Handling null values in Self_Employed
testdf.loc[testdf.Self_Employed.isnull()]

Loan_ID  Gender Married Dependents     Education Self_Employed  \
8    LP001059    Male     Yes          2      Graduate           NaN   
11   LP001082    Male     Yes          1      Graduate           NaN   
13   LP001094    Male     Yes          2      Graduate           NaN   
36   LP001208    Male     Yes          2      Graduate           NaN   
72   LP001375    Male     Yes          1      Graduate           NaN   
89   LP001472  Female      No          0      Graduate           NaN   
142  LP001789    Male     Yes         3+  Not Graduate           NaN   
161  LP001906    Male      No          0      Graduate           NaN   
168  LP001950  Female     Yes         3+      Graduate           NaN   
175  LP001999    Male     Yes          2      Graduate           NaN   
192  LP002069    Male     Yes          2  Not Graduate           NaN   
243  LP002346    Male     Yes          0      Graduate           NaN   
255  LP002399    Male      No          0      Graduate           NaN   
259  LP002415  Female      No          1      Graduate           NaN   
276  LP002542    Male     Yes          0      Graduate           NaN   
278  LP002551    Male     Yes         3+  Not Graduate           NaN   
285  LP002572    Male     Yes          1      Graduate           NaN   
287  LP002584    Male      No          0      Graduate           NaN   
294  LP002610    Male     Yes          1  Not Graduate           NaN   
297  LP002630    Male      No          0  Not Graduate           NaN   
301  LP002651    Male     Yes          1      Graduate           NaN   
323  LP002791    Male      No          1      Graduate           NaN   
326  LP002803    Male     Yes          1  Not Graduate           NaN   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
8              13633                  0       280.0             240.0   
11              2185               1516       162.0             360.0   
13             12173                  0       166.0             360.0   
36              7350               4029       185.0             180.0   
72              4083               1775       139.0              60.0   
89              5058                  0       200.0             360.0   
142             6794                528       139.0             360.0   
161             2964                  0        84.0             360.0   
168             1750               2935        94.0             360.0   
175             4912               4614       160.0             360.0   
192             3785               2912       180.0             360.0   
243             2539               1704       125.0             360.0   
255             2858                  0       123.0             360.0   
259             1850               4583        81.0             360.0   
276             6500                  0       144.0             360.0   
278             3634                910       176.0             360.0   
285             8750                  0       297.0             360.0   
287             1972               4347       106.0             360.0   
294             1792               2565       128.0             360.0   
297             3808                  0        83.0             360.0   
301             6300                  0       125.0             360.0   
323            16000               5000        40.0             360.0   
326             2600                618       122.0             360.0   

     Credit_History Property_Area Loan_Status  
8          1.000000         Urban           Y  
11         1.000000     Semiurban           Y  
13         0.000000     Semiurban           N  
36         1.000000         Urban           Y  
72         1.000000         Urban           Y  
89         1.000000         Rural           Y  
142        0.000000         Urban           N  
161        0.000000     Semiurban           N  
168        0.000000     Semiurban           N  
175        1.000000         Rural           

In [24]:
testdf.loc[(testdf.Self_Employed.isnull())&(testdf.Gender=='Male'), 'Self_Employed'].shape

(20,)

In [31]:
#For Males
testdf.loc[(testdf.Gender=='Male'), 'Self_Employed'].value_counts()

No     255
Yes     31
Name: Self_Employed, dtype: int64

In [30]:
testdf.loc[(testdf.Self_Employed.isnull())&(testdf.Gender=='Male'), 'Self_Employed']= 'No'

In [32]:
#for Females
testdf.loc[(testdf.Gender=='Male'), 'Self_Employed'].value_counts()

No     255
Yes     31
Name: Self_Employed, dtype: int64

In [35]:
testdf.loc[(testdf.Self_Employed.isnull())&(testdf.Gender=='Female'), 'Self_Employed']= 'No'
testdf.loc[testdf.Self_Employed.isnull()]

Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [38]:
### Handling null values in Dependents
testdf.loc[(testdf.Dependents=='0' ), 'Dependents'] = 0
testdf.loc[(testdf.Dependents=='1' ), 'Dependents'] = 1
testdf.loc[(testdf.Dependents=='2' ), 'Dependents'] = 2
testdf.loc[(testdf.Dependents=='3+' ), 'Dependents'] = 4

In [40]:
testdf.loc[testdf.Dependents.isnull()]

Loan_ID  Gender Married Dependents     Education Self_Employed  \
46   LP001237    Male     Yes        NaN  Not Graduate            No   
70   LP001366  Female      No        NaN      Graduate            No   
111  LP001587    Male     Yes        NaN      Graduate            No   
138  LP001769     NaN      No        NaN      Graduate            No   
202  LP002111    Male     Yes        NaN      Graduate            No   
247  LP002360    Male     Yes        NaN      Graduate            No   
251  LP002385    Male     Yes        NaN      Graduate            No   
265  LP002441    Male      No        NaN      Graduate            No   
302  LP002654  Female      No        NaN      Graduate           Yes   
312  LP002754    Male      No        NaN      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
46              4163               1475  162.000000             360.0   
70              3250                  0   95.000000             360.0   
111             4082                  0   93.000000             360.0   
138             3333               1250  110.000000             360.0   
202             3016               1300  100.000000             360.0   
247            10000                  0  139.031915             360.0   
251             3863                  0   70.000000             300.0   
265             3579               3308  138.000000             360.0   
302            14987                  0  177.000000             360.0   
312             2066               2108  104.000000              84.0   

     Credit_History Property_Area Loan_Status  
46           1.0000         Urban           Y  
70           1.0000     Semiurban           Y  
111          1.0000     Semiurban           Y  
138          1.0000     Semiurban           Y  
202          0.8327         Urban           Y  
247          1.0000         Urban           Y  
251          1.0000     Semiurban           Y  
265          0.8327     Semiurban           Y  
302          1.0000         Rural           Y  
312          1.0000         Urban           Y

In [45]:
#for males
testdf.loc[(testdf.Gender=='Male')&(testdf.Education=='Graduate')&(testdf.Self_Employed=='No')&(testdf.Loan_Status=='Y') ,'Dependents'].value_counts()

0    87
1    30
2    27
4    18
Name: Dependents, dtype: int64

In [46]:
testdf.loc[(testdf.Dependents.isnull())&(testdf.Gender=='Male'),'Dependents']= 0

In [47]:
#for females
testdf.loc[(testdf.Gender=='Female')&(testdf.Education=='Graduate')&(testdf.Self_Employed=='No')&(testdf.Loan_Status=='Y') ,'Dependents'].value_counts()

0    26
1     9
2     3
4     2
Name: Dependents, dtype: int64

In [48]:
testdf.loc[(testdf.Dependents.isnull())&(testdf.Gender=='Female'),'Dependents']= 0

In [50]:
testdf.loc[(testdf.Dependents.isnull())]

Loan_ID Gender Married Dependents Education Self_Employed  \
138  LP001769    NaN      No        NaN  Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
138             3333               1250       110.0             360.0   

     Credit_History Property_Area Loan_Status  
138             1.0     Semiurban           Y

In [79]:
testdf['Dependents'].value_counts()

0    209
2     59
1     58
4     40
Name: Dependents, dtype: int64

In [80]:
testdf.loc[(testdf.Dependents.isnull()),'Dependents']= 0
testdf.loc[(testdf.Dependents.isnull())]

Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [52]:
### Handling null values in Gender
testdf.loc[testdf.Gender.isnull()]

Loan_ID Gender Married Dependents     Education Self_Employed  \
22   LP001128    NaN      No          0      Graduate            No   
51   LP001287    NaN     Yes          4  Not Graduate            No   
106  LP001563    NaN      No          0      Graduate            No   
138  LP001769    NaN      No        NaN      Graduate            No   
209  LP002165    NaN      No          1  Not Graduate            No   
231  LP002298    NaN      No          0      Graduate           Yes   
245  LP002355    NaN     Yes          0      Graduate            No   
279  LP002553    NaN      No          0      Graduate            No   
296  LP002614    NaN      No          0      Graduate            No   
303  LP002657    NaN     Yes          1  Not Graduate           Yes   
318  LP002775    NaN      No          0  Not Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
22              3909                  0       101.0             360.0   
51              3500                833       120.0             360.0   
106             1596               1760       119.0             360.0   
138             3333               1250       110.0             360.0   
209             2038               4027       100.0             360.0   
231             2860               2988       138.0             360.0   
245             3186               3145       150.0             180.0   
279            29167                  0       185.0             360.0   
296             6478                  0       108.0             360.0   
303              570               2125        68.0             360.0   
318             4768                  0       125.0             360.0   

     Credit_History Property_Area Loan_Status  
22              1.0         Urban           Y  
51              1.0     Semiurban           Y  
106             0.0         Urban           N  
138             1.0     Semiurban           Y  
209             1.0         Rural           Y  
231             1.0         Urban           Y  
245             0.0     Semiurban           N  
279             1.0     Semiurban           Y  
296             1.0     Semiurban           Y  
303             1.0         Rural           Y  
318             1.0         Rural           Y

In [55]:
#For Males
testdf.loc[(testdf.Married=="Yes")&(testdf.Education=='Graduate')&(testdf.Loan_Status=='Y'),'Gender'].value_counts()

Male      137
Female     17
Name: Gender, dtype: int64

In [58]:
testdf.loc[(testdf.Gender.isnull())&(testdf.Married=="Yes")&(testdf.Education=='Graduate')&(testdf.Loan_Status=='Y'),'Gender']= 'Male'
testdf.loc[testdf.Gender.isnull()]

Loan_ID Gender Married Dependents     Education Self_Employed  \
22   LP001128    NaN      No          0      Graduate            No   
51   LP001287    NaN     Yes          4  Not Graduate            No   
106  LP001563    NaN      No          0      Graduate            No   
138  LP001769    NaN      No        NaN      Graduate            No   
209  LP002165    NaN      No          1  Not Graduate            No   
231  LP002298    NaN      No          0      Graduate           Yes   
245  LP002355    NaN     Yes          0      Graduate            No   
279  LP002553    NaN      No          0      Graduate            No   
296  LP002614    NaN      No          0      Graduate            No   
303  LP002657    NaN     Yes          1  Not Graduate           Yes   
318  LP002775    NaN      No          0  Not Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
22              3909                  0       101.0             360.0   
51              3500                833       120.0             360.0   
106             1596               1760       119.0             360.0   
138             3333               1250       110.0             360.0   
209             2038               4027       100.0             360.0   
231             2860               2988       138.0             360.0   
245             3186               3145       150.0             180.0   
279            29167                  0       185.0             360.0   
296             6478                  0       108.0             360.0   
303              570               2125        68.0             360.0   
318             4768                  0       125.0             360.0   

     Credit_History Property_Area Loan_Status  
22              1.0         Urban           Y  
51              1.0     Semiurban           Y  
106             0.0         Urban           N  
138             1.0     Semiurban           Y  
209             1.0         Rural           Y  
231             1.0         Urban           Y  
245             0.0     Semiurban           N  
279             1.0     Semiurban           Y  
296             1.0     Semiurban           Y  
303             1.0         Rural           Y  
318             1.0         Rural           Y

In [60]:
testdf.loc[(testdf.Married=="No")&(testdf.Education=='Graduate')&(testdf.Dependents==0)&(testdf.Loan_Status=='Y'),'Gender'].value_counts()

Male      47
Female    20
Name: Gender, dtype: int64

In [61]:
testdf.loc[(testdf.Gender.isnull())&(testdf.Married=="No")&(testdf.Education=='Graduate')&(testdf.Dependents==0)&(testdf.Loan_Status=='Y'),'Gender']= 'Male'

In [62]:
testdf.loc[testdf.Gender.isnull()]

Loan_ID Gender Married Dependents     Education Self_Employed  \
51   LP001287    NaN     Yes          4  Not Graduate            No   
106  LP001563    NaN      No          0      Graduate            No   
138  LP001769    NaN      No        NaN      Graduate            No   
209  LP002165    NaN      No          1  Not Graduate            No   
245  LP002355    NaN     Yes          0      Graduate            No   
303  LP002657    NaN     Yes          1  Not Graduate           Yes   
318  LP002775    NaN      No          0  Not Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
51              3500                833       120.0             360.0   
106             1596               1760       119.0             360.0   
138             3333               1250       110.0             360.0   
209             2038               4027       100.0             360.0   
245             3186               3145       150.0             180.0   
303              570               2125        68.0             360.0   
318             4768                  0       125.0             360.0   

     Credit_History Property_Area Loan_Status  
51              1.0     Semiurban           Y  
106             0.0         Urban           N  
138             1.0     Semiurban           Y  
209             1.0         Rural           Y  
245             0.0     Semiurban           N  
303             1.0         Rural           Y  
318             1.0         Rural           Y

In [66]:
testdf.loc[(testdf.Property_Area=="Rural"),'Gender'].value_counts()

Male      17
Female     3
Name: Gender, dtype: int64

In [67]:
testdf.loc[(testdf.Gender.isnull())&(testdf.Property_Area=="Rural"),'Gender']='Male'
testdf.loc[testdf.Gender.isnull()]

Loan_ID Gender Married Dependents     Education Self_Employed  \
51   LP001287    NaN     Yes          4  Not Graduate            No   
106  LP001563    NaN      No          0      Graduate            No   
138  LP001769    NaN      No        NaN      Graduate            No   
245  LP002355    NaN     Yes          0      Graduate            No   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
51              3500                833       120.0             360.0   
106             1596               1760       119.0             360.0   
138             3333               1250       110.0             360.0   
245             3186               3145       150.0             180.0   

     Credit_History Property_Area Loan_Status  
51              1.0     Semiurban           Y  
106             0.0         Urban           N  
138             1.0     Semiurban           Y  
245             0.0     Semiurban           N

In [76]:
testdf.loc[(testdf.Gender.isnull()),'Gender']='Male'
testdf.loc[testdf.Gender.isnull()]

Empty DataFrame
Columns: [Loan_ID, Gender, Married, Dependents, Education, Self_Employed, ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area, Loan_Status]
Index: []

In [81]:
# Analysing null values
null_columns= testdf.columns[testdf.isnull().any()]
testdf[null_columns].isnull().sum()

Series([], dtype: float64)

# Label Encoding

In [82]:
from sklearn.preprocessing import LabelEncoder

In [84]:
# Gender Column
print(testdf['Gender'].unique())
newGender= LabelEncoder()
testdf['Gender']= newGender.fit_transform(testdf['Gender'])
testdf['Gender'].unique()

['Male' 'Female']


array([1, 0])

In [85]:
# Married Column
print(testdf['Married'].unique())
newMarried= LabelEncoder()
testdf['Married']= newMarried.fit_transform(testdf['Married'])
testdf['Married'].unique()

['Yes' 'No']


array([1, 0])

In [86]:
# Property_Area Column
print(testdf['Property_Area'].unique())
newProperty_Area= LabelEncoder()
testdf['Property_Area']= newProperty_Area.fit_transform(testdf['Property_Area'])
testdf['Property_Area'].unique()

['Urban' 'Semiurban' 'Rural']


array([2, 1, 0])

In [88]:
# Education Column
print(testdf['Education'].unique())
newEducation= LabelEncoder()
testdf['Education']= newEducation.fit_transform(testdf['Education'])
testdf['Education'].unique()

['Graduate' 'Not Graduate']


array([0, 1])

In [90]:
# Self_Employed
print(testdf['Self_Employed'].unique())
newSelf_Employed= LabelEncoder()
testdf['Self_Employed']= newSelf_Employed.fit_transform(testdf['Self_Employed'])
testdf['Self_Employed'].unique()

['No' 'Yes']


array([0, 1])

In [91]:
# Loan_Status

print(testdf['Loan_Status'].unique())
newLoan_Status= LabelEncoder()
testdf['Loan_Status']= newLoan_Status.fit_transform(testdf['Loan_Status'])
testdf['Loan_Status'].unique()

['Y' 'N']


array([1, 0])

# Saving Encoded Testing Dataset

In [92]:
testdf.to_csv('encodedTestDf')